.TH KURTOID 6
.SH NAME
Kurtoid \- Bot for the swiss card game "Jassen" developed for the lecture "Deep Learning For Games"
.SH DESCRIPTION
Kurtoid is a simple bot.
.SH BOCKCHAIN
The Bockchain is a cutting-edge concept.
.SH MAXROUND
Maxround is stupid as fuck but smart enough.
.SH AUTHORS
Pascal Kiser <pascal.kiser@stud.hslu.ch> and Patrick Bucher <patrick.bucher@stud.hslu.ch>
